### PR TITLE
Fix naming for LAHS 2024 finals

### PR DESCRIPTION
**Pull request by alaninnovates**
Fix naming for LAHS 2024 finals
The current workaround to adding new schedules is just to use tues/wed/thurs. Fixed by adding new schedules for wed/thurs/fri

### CODE REVIEW

**Comment by avrahnoa-mvla** [comment]
Generally, although more complicated you want to move things back with the numbers in delusional hope that the calendar will be the same next year, but if this merged, it should take priority over the related part in #46

**Comment by alaninnovates** [comment]
You're right - the calendar is going to have finals be on wed/thurs/fri next year. Not sure what the best way to fix this would be.

image

**Comment by alaninnovates** [comment]
Yeah, that would make more sense. Should I keep the naming scheme as finals-wed/thu/fri in order to be backwards-compatible, or make the new (duplicate) schedule that I added be the new finals schedule?

**Comment by alaninnovates** [comment]
Updated to include new finals-day-x schedules!

**Review by nicolaschan — APPROVED** [review]

**Comment by nicolaschan** [comment]
Nice this looks great! In a follow up we can clean up the old finals schedules. That should reduce confusion about which ones to use and we can always check git history if we need to reference them.

**Comment by alaninnovates** [comment]
For the schedule cleanup, do you mean to edit all previous final schedules to conform with the new finals-day-x schedule?

**Comment by nicolaschan** [comment]
I think we can delete the previous finals schedules and corresponding calendar entries if these new ones will cover the foreseeable future.

**Comment by alaninnovates** [comment]
I do get the idea of removing older schedules to prevent confusion, but I was thinking of modifying the old final schedules to conform with the new schedules so that anyone can view previous special calendar days without having to search the git history.

**Comment by nicolaschan** [comment]
Do we expect the previous finals schedules to be used in the future or are they just for reference?

**Comment by nicolaschan** [comment]
Oh, I think I see what you're saying now. This is a good idea. I agree it's useful to keep at least a year of history. We can also consider cleaning up things older than a year because they're unlikely repeat.

**Pull request merged**
