### PR TITLE
Corona Virus School Cancellation Update

### PR DESCRIPTION
**Pull request by rishabg123**

### CODE REVIEW

**Comment by nicolaschan** [comment]
Thanks for submitting this change. Stay safe!

**Comment by rishabg123** [comment]
No problem! You too!

**Comment by rishabg123** [comment]
Hi Nicholas! Sorry to bother you again! The year was off when I made the
change. It should be 2020 instead of 2022. I have created a new pull
request. Can you please merge it ASAP?

Thanks,
Rishab

**Comment by nicolaschan** [comment]
No worries, done.

**Pull request merged**
