### PR TITLE
Added SMHS Bell Schedule

### PR DESCRIPTION
**Pull request by NicosHere**
I followed the template used for the other schools.

Please contact me at contactnicokatzen@gmail.com

👍

### CODE REVIEW

**Comment by nicolaschan** [comment]
Looks good! Thanks so much for your submission. Should be live on bell.plus within the hour (assuming there are no issues).

**Comment by NicosHere** [comment]
Thanks a million!

**Comment by NicosHere** [comment]
Oh and one more thing, I've spread this around my school and I estimate about 1500-2000 unique impressions in the next few days.

**Comment by nicolaschan** [comment]
Awesome! My $5 DigitalOcean droplet should be able to handle that. If you're curious about usage, I finally got the usage stats working again (wait until tomorrow for full results): https://bell.plus/stats

**Pull request merged**
